[package]
name = "boilerplate"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet=">=2.8.4"
openzeppelin = "0.17.0"
cairo_test = "2.8.4"



[scripts]
[[target.starknet-contract]]

casm = true

[tool.voyager]
erc20_contract = {path= "erc20.cairo", address = ""}